### ISSUE TITLE
Timer is 0, stopping the script.

### ISSUE THREAD

**Issue by UnluckySeemo** [Yassine-X/RosettaFucker#1]

**Comment by UnluckySeemo** [comment]
is there any way to run it infinitely ?

**Comment by Yassine-X** [comment]
**

> **Hello and thanks for using my sript !**

** 

> first of all when u ever start running the script ur going to get a free 30 min (free trial) ,but after that if u need more u can contact me on my discord server [here](https://discord.ggW7dpT89r3H)
